platform:
  - x86
  - x64
  
configuration:
  - Release

os:
  - Visual Studio 2015 RC
  
build_script:
  - md build
  - cd build
  - cmake -DCPPTEST_LITE_CREATE_TESTS=ON -G"Visual Studio 14 2015" ..
  - cmake --build .
  
after_build:
  - build\Debug\testCppTestLite.exe